version: '3.7'

services:
  web-app:
    build: .
    restart: always
    entrypoint: "/api_app/start.sh"
    env_file: .env_web-app
    ports:
      - "8088:8088"
    depends_on:
      - db

  db:
    image: postgres:16.4
    container_name: db_app
    env_file: .env_db
    volumes:
       - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: