"""0005_edit_lazy_in_fields

Revision ID: 622c6bee060d
Revises: 4401de4e55d1
Create Date: 2024-09-24 14:07:38.278344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '622c6bee060d'
down_revision: Union[str, None] = '4401de4e55d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
