"""0007_add_price_fields

Revision ID: c6b9f5c03182
Revises: 622c6bee060d
Create Date: 2024-09-25 15:33:18.156255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6b9f5c03182'
down_revision: Union[str, None] = '622c6bee060d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('price', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'price')
    op.drop_column('order_items', 'price')
    # ### end Alembic commands ###
